# Wine

### Introduction:

This exercise is a adaptation from the UCI Wine dataset.
The only pupose is to practice deleting data with pandas.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data).

### Step 3. Assign it to a variable called wine

In [19]:
wine = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",names=range(14))

### Step 4. Delete the first, fourth, seventh, nineth, eleventh, thirteenth and fourteenth columns

In [25]:
wine = wine.drop(columns=wine.columns[[0,3,6,8,11,12,13]])

### Step 5. Assign the columns as below:

The attributes are (donated by Riccardo Leardi, riclea '@' anchem.unige.it):  
1) alcohol  
2) malic_acid  
3) alcalinity_of_ash  
4) magnesium  
5) flavanoids  
6) proanthocyanins  
7) hue

In [26]:
wine.columns = ['alcohol', 'malic_acid', 'alcalinity_of_ash', 'magnesium', 'flavanoids', 'proanthocyanins', 'hue']
wine.head()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,14.23,1.71,15.6,127,3.06,2.29,5.64
1,13.20,1.78,11.2,100,2.76,1.28,4.38
2,13.16,2.36,18.6,101,3.24,2.81,5.68
3,14.37,1.95,16.8,113,3.49,2.18,7.80
4,13.24,2.59,21.0,118,2.69,1.82,4.32

### Step 6. Set the values of the first 3 rows from alcohol as NaN

In [36]:
wine.iloc[:3,0]=None
wine.head()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.71,15.6,127,3.06,2.29,5.64
1,NaN,1.78,11.2,100,2.76,1.28,4.38
2,NaN,2.36,18.6,101,3.24,2.81,5.68
3,14.37,1.95,16.8,113,3.49,2.18,7.80
4,13.24,2.59,21.0,118,2.69,1.82,4.32

### Step 7. Now set the value of the rows 3 and 4 of magnesium as NaN

In [37]:
wine.iloc[2:4,3]=None
wine.head()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.71,15.6,127.0,3.06,2.29,5.64
1,NaN,1.78,11.2,100.0,2.76,1.28,4.38
2,NaN,2.36,18.6,NaN,3.24,2.81,5.68
3,14.37,1.95,16.8,NaN,3.49,2.18,7.80
4,13.24,2.59,21.0,118.0,2.69,1.82,4.32

### Step 8. Fill the value of NaN with the number 10 in alcohol and 100 in magnesium

In [41]:
wine["alcohol"]=wine["alcohol"].fillna(10)
wine["magnesium"]=wine["magnesium"].fillna(100)
wine.head()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,10.00,1.71,15.6,127.0,3.06,2.29,5.64
1,10.00,1.78,11.2,100.0,2.76,1.28,4.38
2,10.00,2.36,18.6,100.0,3.24,2.81,5.68
3,14.37,1.95,16.8,100.0,3.49,2.18,7.80
4,13.24,2.59,21.0,118.0,2.69,1.82,4.32

### Step 9. Count the number of missing values

In [42]:
wine.isna().sum()

alcohol              0
malic_acid           0
alcalinity_of_ash    0
magnesium            0
flavanoids           0
proanthocyanins      0
hue                  0
dtype: int64

### Step 10.  Create an array of 10 random numbers up until 10

In [47]:
import numpy as np
random_number = np.random.randint(0,10,10)

### Step 11.  Use random numbers you generated as an index and assign NaN value to each of cell.

In [51]:
wine["alcohol"][random_number]=None
wine.head(10)

C:\Users\shich\AppData\Local\Temp\ipykernel_10772\1718169924.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  wine["alcohol"][random_number]=None

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
0,NaN,1.71,15.6,127.0,3.06,2.29,5.64
1,NaN,1.78,11.2,100.0,2.76,1.28,4.38
2,NaN,2.36,18.6,100.0,3.24,2.81,5.68
3,NaN,1.95,16.8,100.0,3.49,2.18,7.80
4,NaN,2.59,21.0,118.0,2.69,1.82,4.32
5,14.20,1.76,15.2,112.0,3.39,1.97,6.75
6,NaN,1.87,14.6,96.0,2.52,1.98,5.25
7,14.06,2.15,17.6,121.0,2.51,1.25,5.05
8,14.83,1.64,14.0,97.0,2.98,1.98,5.20
9,13.86,1.35,16.0,98.0,3.15,1.85,7.22

### Step 12.  How many missing values do we have?

In [52]:
wine.isna().sum()

alcohol              6
malic_acid           0
alcalinity_of_ash    0
magnesium            0
flavanoids           0
proanthocyanins      0
hue                  0
dtype: int64

### Step 13. Delete the rows that contain missing values

In [53]:
wine.dropna()

,alcohol,malic_acid,alcalinity_of_ash,magnesium,flavanoids,proanthocyanins,hue
5,14.20,1.76,15.2,112.0,3.39,1.97,6.75
7,14.06,2.15,17.6,121.0,2.51,1.25,5.05
8,14.83,1.64,14.0,97.0,2.98,1.98,5.20
9,13.86,1.35,16.0,98.0,3.15,1.85,7.22
10,14.10,2.16,18.0,105.0,3.32,2.38,5.75
...,...,...,...,...,...,...,...
173,13.71,5.65,20.5,95.0,0.61,1.06,7.70
174,13.40,3.91,23.0,102.0,0.75,1.41,7.30
175,13.27,4.28,20.0,120.0,0.69,1.35,10.20
176,13.17,2.59,20.0,120.0,0.68,1.46,9.30
177,14.13,4.10,24.5,96.0,0.76,1.35,9.20

### Step 14. Print only the non-null values in alcohol

### Step 15.  Reset the index, so it starts with 0 again

### BONUS: Create your own question and answer it.