# Investor - Flow of Funds - US

### Introduction:

Special thanks to: https://github.com/rgrp for sharing the dataset.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv).

### Step 3. Assign it to a variable called

In [14]:
df = pd.read_csv("https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv")
df

,Date,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
0,2011-10-05,-4002,-4499.0,497,-1354.0,-5828,-6258.0,430,-11184.0
1,2011-10-12,-7397,-5842.0,-1555,512.0,3954,3927.0,28,-2931.0
2,2011-10-19,-3292,-3466.0,174,1399.0,5652,5102.0,550,3759.0
3,2011-10-26,-3696,-2998.0,-698,2631.0,4910,4070.0,841,3846.0
4,2011-12-07,-7956,-5761.0,-2196,1089.0,3523,2068.0,1456,-3343.0
...,...,...,...,...,...,...,...,...,...
157,2024-11-26,37441,NaN,29996,NaN,29616,NaN,380,NaN
158,2024-12-04,27170,NaN,22014,NaN,22510,NaN,-496,NaN
159,2024-12-11,36551,NaN,28883,NaN,29251,NaN,-368,NaN
160,2024-12-18,22891,NaN,26962,NaN,20604,NaN,6358,NaN
161,2024-12-24,35210,NaN,36142,NaN,32529,NaN,3613,NaN

### Step 4.  What is the frequency of the dataset?

In [15]:
df["Date"]=pd.to_datetime(df["Date"])

In [16]:
(df["Date"][1]-df["Date"][0]).days

7

### Step 5. Set the column Date as the index.

In [17]:
df = df.set_index("Date")

### Step 6. What is the type of the index?

In [18]:
type(df.index)

pandas.core.indexes.datetimes.DatetimeIndex

### Step 7. Set the index to a DatetimeIndex type

### Step 8.  Change the frequency to monthly, sum the values and assign it to monthly.

In [21]:
monthly = df.resample("ME").sum()
monthly

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2011-10-31,-18387,-16805.0,-1582,3188.0,8688,6841.0,1849,-6510.0
2011-11-30,0,0.0,0,0.0,0,0.0,0,0.0
2011-12-31,-23657,-16659.0,-6999,2395.0,13817,9335.0,4483,-7443.0
2012-01-31,0,0.0,0,0.0,0,0.0,0,0.0
2012-02-29,0,0.0,0,0.0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...
2024-08-31,0,0.0,0,0.0,0,0.0,0,0.0
2024-09-30,0,0.0,0,0.0,0,0.0,0,0.0
2024-10-31,0,0.0,0,0.0,0,0.0,0,0.0
2024-11-30,157317,0.0,126974,0.0,124253,0.0,2721,0.0
2024-12-31,121822,0.0,114001,0.0,104894,0.0,9107,0.0

### Step 9. You will notice that it filled the dataFrame with months that don't have any data with NaN. Let's drop these rows.

In [23]:
monthly = monthly.dropna()

### Step 10. Good, now we have the monthly data. Now change the frequency to year.

In [26]:
monthly.resample("YS").sum()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2011-01-01,-42044,-33464.0,-8581,5583.0,22505,16176.0,6332,-13953.0
2012-01-01,-23929,-22012.0,-1915,785.0,9828,12491.0,-2663,-13316.0
2013-01-01,8052,-5562.0,13615,4180.0,-24460,-14209.0,-10251,-12227.0
2014-01-01,-17011,-15124.0,-1887,-6141.0,-14400,-19014.0,4614,-37552.0
2015-01-01,-36337,-25116.0,-11221,-12474.0,-28678,-34571.0,5893,-77489.0
2016-01-01,0,0.0,0,0.0,0,0.0,0,0.0
2017-01-01,-51270,-54927.0,3657,-10514.0,26158,26360.0,-204,-35625.0
2018-01-01,0,0.0,0,0.0,0,0.0,0,0.0
2019-01-01,-58200,-48830.0,-9370,-10874.0,37307,20486.0,16820,-31766.0
2020-01-01,-66618,-40387.0,-26231,-2972.0,60423,50781.0,9643,-9170.0
2021-01-01,0,0.0,0,0.0,0,0.0,0,0.0
2022-01-01,303588,0.0,197245,0.0,159480,0.0,37764,0.0
2023-01-01,577344,0.0,384041,0.0,301862,0.0,82177,0.0
2024-01-01,780438,0.0,603567,0.0,541533,0.0,62031,0.0

### BONUS: Create your own question and answer it.