# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [2]:
baby_names = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv")

### Step 4. See the first 10 entries

In [3]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [5]:
baby_names.drop(columns=["Unnamed: 0","Id"],inplace=True)

### Step 6. Is there more male or female names in the dataset?

In [6]:
baby_names["Gender"].value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

### Step 7. Group the dataset by name and assign to names

In [14]:
names = baby_names.groupby("Name")

         Year  Gender  State  Count
Name
Riley    1112    1112   1112   1112
Avery    1080    1080   1080   1080
Jordan   1073    1073   1073   1073
Peyton   1064    1064   1064   1064
Hayden   1049    1049   1049   1049
...       ...     ...    ...    ...
Ethon       1       1      1      1
Malajah     1       1      1      1
Euan        1       1      1      1
Azyria      1       1      1      1
Nissen      1       1      1      1

[17632 rows x 4 columns]

### Step 8. How many different names exist in the dataset?

In [15]:
len(names["Count"].count())

17632

### Step 9. What is the name with most occurrences?

In [37]:
names.sum()[["Count"]].sort_values("Count",ascending=False)

             Count
Name
Jacob       242874
Emma        214852
Michael     214405
Ethan       209277
Isabella    204798
...            ...
Eniola           5
Atlantis         5
Marci            5
Simarpreet       5
Nita             5

[17632 rows x 1 columns]

### Step 10. How many different names have the least occurrences?

In [46]:
count_df = names.sum()[["Count"]].sort_values("Count")
count_df[count_df["Count"]==count_df["Count"].min()]

             Count
Name
Destenie         5
Janisha          5
Lizvet           5
Arsalan          5
Janira           5
...            ...
Alyxandria       5
Ethanjoseph      5
Almira           5
Davarion         5
Xoey             5

[2578 rows x 1 columns]

### Step 11. What is the median name occurrence?

In [48]:
count_df[count_df["Count"]==count_df["Count"].median()]

            Count
Name
Caleah         49
Anely          49
Alysse         49
Emmanuela      49
Carlota        49
...           ...
Sanjuanita     49
Jeovany        49
Deante         49
Jaice          49
Leylanie       49

[66 rows x 1 columns]

### Step 12. What is the standard deviation of names?

In [51]:
count_df["Count"].std()

np.float64(11006.06946789057)

### Step 13. Get a summary with the mean, min, max, std and quartiles.

In [53]:
count_df.describe()

               Count
count   17632.000000
mean     2008.932169
std     11006.069468
min         5.000000
25%        11.000000
50%        49.000000
75%       337.000000
max    242874.000000